name: flutter_clean_bloc
description: A Flutter project to demonstrate the simplicity of an approach of a Clean Architecture with BloC pattern.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  http: ^0.13.3
  json_annotation: ^4.0.1
  nuvigator: 
    path: ../nuvigator
  provider: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.4
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
