name: PR Validation

on: 
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Flutter - Analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Clone nuvigator
        working-directory: ./..
        run: |
          ls
          git clone -b add-null-safety-support https://github.com/lubritto/nuvigator.git
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --dry-run --set-exit-if-changed lib/ test/
      - run: flutter test --coverage --machine > test-results.json
      - uses: dorny/test-reporter@v1.4.2
        with:
          name: Test Results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 85